// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package common

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

const (
	TestIntConstant = 1234
)

type TestEnum int64

const (
	TestEnum_Enum1 TestEnum = 1
	TestEnum_Enum2 TestEnum = 2
	TestEnum_Enum3 TestEnum = 10
)

func (p TestEnum) String() string {
	switch p {
	case TestEnum_Enum1:
		return "Enum1"
	case TestEnum_Enum2:
		return "Enum2"
	case TestEnum_Enum3:
		return "Enum3"
	}
	return "<UNSET>"
}

func TestEnumFromString(s string) (TestEnum, error) {
	switch s {
	case "Enum1":
		return TestEnum_Enum1, nil
	case "Enum2":
		return TestEnum_Enum2, nil
	case "Enum3":
		return TestEnum_Enum3, nil
	}
	return TestEnum(0), fmt.Errorf("not a valid TestEnum string")
}

func TestEnumPtr(v TestEnum) *TestEnum { return &v }
func (p *TestEnum) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TestEnum(result.Int64)
	return
}

func (p *TestEnum) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TestInteger = int32

type TestStruct struct {
	SBool         bool             `thrift:"sBool,1" frugal:"1,default,bool" json:"sBool"`
	SBoolReq      bool             `thrift:"sBoolReq,2,required" frugal:"2,required,bool" json:"sBoolReq"`
	SBoolOpt      *bool            `thrift:"sBoolOpt,3,optional" frugal:"3,optional,bool" json:"sBoolOpt,omitempty"`
	SListString   []string         `thrift:"sListString,4" frugal:"4,default,list<string>" json:"sListString"`
	SSetI16       []int16          `thrift:"sSetI16,5" frugal:"5,default,set<i16>" json:"sSetI16"`
	SMapI32String map[int32]string `thrift:"sMapI32String,6" frugal:"6,default,map<i32:string>" json:"sMapI32String"`
}

func NewTestStruct() *TestStruct {
	return &TestStruct{}
}

func (p *TestStruct) InitDefault() {
}

func (p *TestStruct) GetSBool() (v bool) {
	return p.SBool
}

func (p *TestStruct) GetSBoolReq() (v bool) {
	return p.SBoolReq
}

var TestStruct_SBoolOpt_DEFAULT bool

func (p *TestStruct) GetSBoolOpt() (v bool) {
	if !p.IsSetSBoolOpt() {
		return TestStruct_SBoolOpt_DEFAULT
	}
	return *p.SBoolOpt
}

func (p *TestStruct) GetSListString() (v []string) {
	return p.SListString
}

func (p *TestStruct) GetSSetI16() (v []int16) {
	return p.SSetI16
}

func (p *TestStruct) GetSMapI32String() (v map[int32]string) {
	return p.SMapI32String
}
func (p *TestStruct) SetSBool(val bool) {
	p.SBool = val
}
func (p *TestStruct) SetSBoolReq(val bool) {
	p.SBoolReq = val
}
func (p *TestStruct) SetSBoolOpt(val *bool) {
	p.SBoolOpt = val
}
func (p *TestStruct) SetSListString(val []string) {
	p.SListString = val
}
func (p *TestStruct) SetSSetI16(val []int16) {
	p.SSetI16 = val
}
func (p *TestStruct) SetSMapI32String(val map[int32]string) {
	p.SMapI32String = val
}

func (p *TestStruct) IsSetSBoolOpt() bool {
	return p.SBoolOpt != nil
}

func (p *TestStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestStruct(%+v)", *p)
}

var fieldIDToName_TestStruct = map[int16]string{
	1: "sBool",
	2: "sBoolReq",
	3: "sBoolOpt",
	4: "sListString",
	5: "sSetI16",
	6: "sMapI32String",
}
