// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package service

import (
	"context"
	"fmt"
	"kit/kitex_gen/kit/common"
)

type TestRequest struct {
	Msg string             `thrift:"msg,1" frugal:"1,default,string" json:"msg"`
	S   *common.TestStruct `thrift:"s,2" frugal:"2,default,common.TestStruct" json:"s"`
}

func NewTestRequest() *TestRequest {
	return &TestRequest{}
}

func (p *TestRequest) InitDefault() {
}

func (p *TestRequest) GetMsg() (v string) {
	return p.Msg
}

var TestRequest_S_DEFAULT *common.TestStruct

func (p *TestRequest) GetS() (v *common.TestStruct) {
	if !p.IsSetS() {
		return TestRequest_S_DEFAULT
	}
	return p.S
}
func (p *TestRequest) SetMsg(val string) {
	p.Msg = val
}
func (p *TestRequest) SetS(val *common.TestStruct) {
	p.S = val
}

func (p *TestRequest) IsSetS() bool {
	return p.S != nil
}

func (p *TestRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestRequest(%+v)", *p)
}

var fieldIDToName_TestRequest = map[int16]string{
	1: "msg",
	2: "s",
}

type TestResponse struct {
	Msg string             `thrift:"msg,1" frugal:"1,default,string" json:"msg"`
	S   *common.TestStruct `thrift:"s,2" frugal:"2,default,common.TestStruct" json:"s"`
}

func NewTestResponse() *TestResponse {
	return &TestResponse{}
}

func (p *TestResponse) InitDefault() {
}

func (p *TestResponse) GetMsg() (v string) {
	return p.Msg
}

var TestResponse_S_DEFAULT *common.TestStruct

func (p *TestResponse) GetS() (v *common.TestStruct) {
	if !p.IsSetS() {
		return TestResponse_S_DEFAULT
	}
	return p.S
}
func (p *TestResponse) SetMsg(val string) {
	p.Msg = val
}
func (p *TestResponse) SetS(val *common.TestStruct) {
	p.S = val
}

func (p *TestResponse) IsSetS() bool {
	return p.S != nil
}

func (p *TestResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestResponse(%+v)", *p)
}

var fieldIDToName_TestResponse = map[int16]string{
	1: "msg",
	2: "s",
}

type TestService interface {
	TMethod(ctx context.Context, req *TestRequest) (r *TestResponse, err error)
}

type TestServiceTMethodArgs struct {
	Req *TestRequest `thrift:"req,1" frugal:"1,default,TestRequest" json:"req"`
}

func NewTestServiceTMethodArgs() *TestServiceTMethodArgs {
	return &TestServiceTMethodArgs{}
}

func (p *TestServiceTMethodArgs) InitDefault() {
}

var TestServiceTMethodArgs_Req_DEFAULT *TestRequest

func (p *TestServiceTMethodArgs) GetReq() (v *TestRequest) {
	if !p.IsSetReq() {
		return TestServiceTMethodArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TestServiceTMethodArgs) SetReq(val *TestRequest) {
	p.Req = val
}

func (p *TestServiceTMethodArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TestServiceTMethodArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceTMethodArgs(%+v)", *p)
}

var fieldIDToName_TestServiceTMethodArgs = map[int16]string{
	1: "req",
}

type TestServiceTMethodResult struct {
	Success *TestResponse `thrift:"success,0,optional" frugal:"0,optional,TestResponse" json:"success,omitempty"`
}

func NewTestServiceTMethodResult() *TestServiceTMethodResult {
	return &TestServiceTMethodResult{}
}

func (p *TestServiceTMethodResult) InitDefault() {
}

var TestServiceTMethodResult_Success_DEFAULT *TestResponse

func (p *TestServiceTMethodResult) GetSuccess() (v *TestResponse) {
	if !p.IsSetSuccess() {
		return TestServiceTMethodResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TestServiceTMethodResult) SetSuccess(x interface{}) {
	p.Success = x.(*TestResponse)
}

func (p *TestServiceTMethodResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestServiceTMethodResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TestServiceTMethodResult(%+v)", *p)
}

var fieldIDToName_TestServiceTMethodResult = map[int16]string{
	0: "success",
}
